name: Java Maven Install on self hosted 

on:
  workflow_dispatch:

jobs:
  install_maven:
    runs-on: self-hosted
    steps:
    - name: Download Maven
      run: |
        Invoke-WebRequest -Uri 'https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip' -OutFile 'maven.zip'
        Expand-Archive -Path 'maven.zip' -DestinationPath 'C:\tools'
    - name: Set up Maven
      run: |
        $env:PATH += ";C:\tools\apache-maven-3.9.6\bin"
        mvn -version
