name: Java Maven Build & Publish Artifact

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: C:\tools\apache-maven-3.9.6\bin\mvn -B package --file pom.xml

  publish-job:
    runs-on: self-hosted
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify Maven build output
      run: |
        ls -R
    - run: C:\tools\apache-maven-3.9.6\bin\mvn --batch-mode --update-snapshots verify
    - name: List files in Maven directory
      run: |
        ls -R C:\github\actions-runner\_work\maven\maven
    - run: |
        mkdir staging  
        if (Test-Path 'C:\github\actions-runner\_work\maven\maven\target') {
          cp C:\github\actions-runner\_work\maven\maven\target\*.jar staging
        } else {
          Write-Host "Target directory not found"
          exit 1
        }
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
