name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install_maven:
    runs-on: self-hosted
    steps:
    - name: Check if Maven is installed
      run: |
        if (!(Test-Path "$(Get-Command mvn -ErrorAction SilentlyContinue).Source")) {
          Write-Host "Maven is not installed, proceeding with installation..."
          # Place installation steps here
        } else {
          Write-Host "Maven is already installed."
        }

  build_test:
    needs: install_maven
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: C:\tools\apache-maven-3.9.6\bin\mvn -B package --file pom.xml

  publish-job:
    runs-on: self-hosted
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: C:\tools\apache-maven-3.9.6\bin\mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
